### ISSUE TITLE
Docs: fix known issues metrics-server custom values

### ISSUE THREAD

**Issue by SamuelLHuber** [linode/apl-core#1660]
**Describe the bug:** (a clear and concise description of what the bug is)

**To Reproduce**

1. Go to https://otomi.io/docs/get-started/installation/known-issues
2. Try the described custom values on deployment via 
```
helm repo add apl https://linode.github.io/apl-core/
helm repo update
helm install apl apl/otomi -f values-linodeapl.yaml
```

then it will fail with ```Error: YAML parse error on metrics-server/templates/deployment.yaml: error converting YAML to JSON: yaml: line 66: did not find expected '-' indicator ```

which can be fixed by using

```
apps:
  metrics-server:
    enabled: true
    _rawValues:
      extraArgs:
        - --kubelet-preferred-address-types=InternalIP
        - --kubelet-insecure-tls=true
```
